spring:
  application:
    name: kcdc-mcp
  main:
    web-application-type: servlet
    banner-mode: log
  ai:
    mcp:
      server:
        stdio: false
        type: sync
        name: kcdc-sessions-mcp
        version: 0.0.1
        enabled: true
        instructions: "This server provides session catalog data for KCDC 2025"

server:
  port: 8080

logging:
  level:
    dev.danvega: INFO
    org.springframework.ai: INFO